url: "https://mountainmankrist.github.io/blackochlera" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "www" # the subpath of your site, e.g. /blog
title: "Bläck och lera" # the name of your site, e.g. ACME Corp.
email: "goranbergmankristiansson@gmail.com"
author: "Göran Kristiansson"
description: "Tatueringar, keramik och konst."

defaults:
  -
    scope:
      path: "assets/images/kristin"
    values:
      folder: "kristin"
  -
    scope:
      path: "assets/images/ingrid"
    values:
      folder: "ingrid"
  -
    scope:
      path: "assets/images/kerstin"
    values:
      folder: "kerstin"
  -
    scope:
      path: "assets/images/studion"
    values:
      folder: "studion"

# Build settings (Q: Is this needed?)

# Google maps
maps:
  google:
    api_key: AIzaSyBD64fXXZHGQr-E6R0x01hYfEsvhEOaZ-k

# Google Analytics
google_analytics: UA-154203542-1
  